apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elasticsearch-demo-app3
spec:
  template:
    spec:
      containers:
        - name: kibana
          env:
            - name: SERVER_PUBLICBASEURL
              value: https://kibana-demo.apps.asagare-c1.qe.rh-ocs.com
            - name: SERVER_NAME
              value: kibana-demo.apps.asagare-c1.qe.rh-ocs.com
